### ISSUE TITLE
bcc compilation on target board failed

### ISSUE THREAD

**Issue by rongqianfeng** [joelagnel/adeb#12] opened 2018-08-13 04:19 UTC
Hi,
I am trying to get adeb-BCC working on a Hikey970 android platform.
By  default, use the command “adeb prepare --build --bcc --kernelsrc usr/src/linux-4.9.119” to compile bcc is failed.

The error information are as follows：
bash: cannot set terminal process group (16629): Inappropriate ioctl for device
bash: no job control in this shell
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler: /usr/bin/clang-6.0
-- Check for working C compiler: /usr/bin/clang-6.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-6.0
-- Check for working CXX compiler: /usr/bin/clang++-6.0 -- broken
CMake Error at /usr/share/cmake-3.11/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/usr/bin/clang++-6.0"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /bcc-master/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_7686c/fast"
    /usr/bin/make -f CMakeFiles/cmTC_7686c.dir/build.make CMakeFiles/cmTC_7686c.dir/build
    make[1]: Entering directory '/bcc-master/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_7686c.dir/testCXXCompiler.cxx.o
    /usr/bin/clang++-6.0     -o CMakeFiles/cmTC_7686c.dir/testCXXCompiler.cxx.o -c /bcc-master/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_7686c
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7686c.dir/link.txt --verbose=1
    /usr/bin/clang++-6.0       -rdynamic CMakeFiles/cmTC_7686c.dir/testCXXCompiler.cxx.o  -o cmTC_7686c 
    /usr/bin/ld: cannot find -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_7686c.dir/build.make:87: cmTC_7686c] Error 1
    make[1]: Leaving directory '/bcc-master/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:126: cmTC_7686c/fast] Error 2

**Comment by rongqianfeng** [comment] 2018-08-13 07:15
Hi,
 I try the methods of @Linuxuser4 provide as follows，the bcc compilation on target board success.

1. A softlink to stdc++ was required since compilation complained of missing stdc++ library.
ln -s /usr/lib/gcc/aarch64-linux-gnu/7/libstdc++.so /usr/lib/libstdc++.so

2.Two include paths needed to be provided to avoid missing header error. These were added in CMakeLists.txt in the base folder:
include_directories(/usr/include/c++/7/)
include_directories(/usr/include/aarch64-linux-gnu/c++/7/)

When run the command "funclatency do_sys_open" generate Issue 1: Headers are missing on the target device, but I don't know how to solve this problem.
root@localhost:/# funclatency do_sys_open
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:5:
include/uapi/linux/types.h:4:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/funclatency", line 206, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text

**Comment by iotcg** [comment] 2018-08-13 09:26
I enabled adeb on x86 platform. The issue is resolved in:
https://github.com/iotcg/adeb/tree/develop

**Comment by iotcg** [comment] 2018-08-15 10:53
It's kernel head file issues.
Two suspect points:
1. Some kernel head files are not copied into kernel-headers.
2. Need more specific CPATH to include the directory to tell gcc/clang to find the header file.

BTW, you can refer to below file to generate kernel-headers:
         https://github.com/iotcg/adeb/blob/develop/kernel-headers.sh
As you know, we often build kernel out of kernel source directory, e.g. build_kernel.
You can put kernel-header.sh under build_kernel and run the script, it will generate kernel-headers directory which includes all the required kernel head files.

**Comment by joelagnel** [comment] 2018-08-16 15:27
Give us a day. We fixed the compilation issue. Pushing it

**Comment by iotcg** [comment] 2018-08-16 15:35
@joelagnel Glad to see your fix, waiting for PR. I also want to know how to resolve "library link issue" & "include head file issue" besides my method.

**Comment by joelagnel** [comment] 2018-08-16 20:33
Actually, the issue I was talking about is different. Your compilation could be failing because of incorrect 'kernel-headers' as you pointed:
```
/kernel-headers/include/linux/falloc.h:12:2: error: unknown type name '__s16'
```
Erick is working on removing dependency on kernel headers. His prototype is already working but it has to be merged. It will be merged either today or tomorrow. After that the following command should work:
“adeb prepare --build --bcc`

We will update you today or tomorrow. Thanks for the patience and for your help in making Androdeb better.

**Comment by joelagnel** [comment] 2018-08-16 20:33
CC @ErickReyesR

**Comment by joelagnel** [comment] 2018-08-16 20:37
@iotcg thanks for sharing your header build script. Could you send me a pull-request to add out-of-tree kernel header build support to `--kernelsrc` option? I think we will also need additional options maybe: `--kernelsrc` and `--kernelout` ?

**Comment by joelagnel** [comment] 2018-08-16 20:37
Also as I was saying, we will also provide "backup" kernel headers incase `--kernelsrc` option is skipped which @ErickReyesR is working on.

**Comment by iotcg** [comment] 2018-08-17 09:27
@joelagnel Per your request, PR: https://github.com/joelagnel/adeb/pull/13
This PR has been verified on local host and target device. It supports extract kernel headers when building kernel out-of-tree.

**Comment by joelagnel** [comment] 2019-01-16 13:54
At the moment, I feel out-of-tree header building will complicate the flow too much. Also we have eliminated the need for kernel version as long as you are running a recent LTS kernel (headers will be automatically downloaded). For that reason, I am closing this. Thanks

**Closed by joelagnel** 2019-01-16 13:54 UTC
